[colors]
artwork_area = "#eff1f5"
background = "#eff1f5"
border = "#acb0be"
border_focused = "#1e66f5"
error = "#d20f39"
foreground = "#4c4f69"
highlight = "#df8e1d"
lyrics_background = "#eff1f5"
lyrics_border = "#acb0be"
lyrics_border_focused = "#1e66f5"
lyrics_highlight = "#1e66f5"
lyrics_text = "#8c8fa1"
paused = "#df8e1d"
playing = "#40a02b"
popup_border = "#ea76cb"
progress = "#1e66f5"
selection = "#7287fd"
separator = "#acb0be"
status_line = "#4c4f69"
stopped = "#acb0be"
success = "#40a02b"
text_muted = "#8c8fa1"
time_text = "#4c4f69"
warning = "#df8e1d"
