[colors]
artwork_area = "#282a36"
background = "#282a36"
border = "#44475a"
border_focused = "#bd93f9"
error = "#ff5555"
foreground = "#f8f8f2"
highlight = "#f1fa8c"
lyrics_background = "#282a36"
lyrics_border = "#44475a"
lyrics_border_focused = "#bd93f9"
lyrics_highlight = "#8be9fd"
lyrics_text = "#6272a4"
paused = "#f1fa8c"
playing = "#50fa7b"
popup_border = "#ff79c6"
progress = "#8be9fd"
selection = "#44475a"
separator = "#44475a"
status_line = "#f8f8f2"
stopped = "#6272a4"
success = "#50fa7b"
text_muted = "#6272a4"
time_text = "#f8f8f2"
warning = "#f1fa8c"
