[colors]
artwork_area = "#272e33"
background = "#272e33"
border = "#414b50"
border_focused = "#7fbbb3"
error = "#e67e80"
foreground = "#d3c6aa"
highlight = "#dbbc7f"
lyrics_background = "#272e33"
lyrics_border = "#414b50"
lyrics_border_focused = "#7fbbb3"
lyrics_highlight = "#7fbbb3"
lyrics_text = "#414b50"
paused = "#dbbc7f"
playing = "#a7c080"
popup_border = "#d699b6"
progress = "#7fbbb3"
selection = "#414b50"
separator = "#414b50"
status_line = "#d3c6aa"
stopped = "#414b50"
success = "#a7c080"
text_muted = "#414b50"
time_text = "#d3c6aa"
warning = "#dbbc7f"
