[colors]
artwork_area = "#282828"
background = "#282828"
border = "#928374"
border_focused = "#d65d0e"
error = "#cc241d"
foreground = "#ebdbb2"
highlight = "#d79921"
lyrics_background = "#282828"
lyrics_border = "#928374"
lyrics_border_focused = "#d65d0e"
lyrics_highlight = "#458588"
lyrics_text = "#a89984"
paused = "#d79921"
playing = "#98971a"
popup_border = "#458588"
progress = "#458588"
selection = "#504945"
separator = "#928374"
status_line = "#ebdbb2"
stopped = "#928374"
success = "#98971a"
text_muted = "#a89984"
time_text = "#ebdbb2"
warning = "#d79921"
