[colors]
artwork_area = "#fbf1c7"
background = "#fbf1c7"
border = "#928374"
border_focused = "#458588"
error = "#cc241d"
foreground = "#3c3836"
highlight = "#d79921"
lyrics_background = "#fbf1c7"
lyrics_border = "#928374"
lyrics_border_focused = "#458588"
lyrics_highlight = "#458588"
lyrics_text = "#928374"
paused = "#d79921"
playing = "#98971a"
popup_border = "#b16286"
progress = "#458588"
selection = "#d5c4a1"
separator = "#928374"
status_line = "#3c3836"
stopped = "#928374"
success = "#98971a"
text_muted = "#928374"
time_text = "#3c3836"
warning = "#d79921"
