[colors]
artwork_area = "#1c1e26"
background = "#1c1e26"
border = "#2e303e"
border_focused = "#26bbd9"
error = "#e95678"
foreground = "#d5d8da"
highlight = "#fab795"
lyrics_background = "#1c1e26"
lyrics_border = "#2e303e"
lyrics_border_focused = "#26bbd9"
lyrics_highlight = "#59e1e3"
lyrics_text = "#2e303e"
paused = "#fab795"
playing = "#29d398"
popup_border = "#ee64ac"
progress = "#59e1e3"
selection = "#6c6f93"
separator = "#2e303e"
status_line = "#d5d8da"
stopped = "#2e303e"
success = "#29d398"
text_muted = "#2e303e"
time_text = "#d5d8da"
warning = "#fab795"
