[colors]
artwork_area = "#161821"
background = "#161821"
border = "#6b7089"
border_focused = "#84a0c6"
error = "#e27878"
foreground = "#c6c8d1"
highlight = "#e2a478"
lyrics_background = "#161821"
lyrics_border = "#6b7089"
lyrics_border_focused = "#84a0c6"
lyrics_highlight = "#89b8c2"
lyrics_text = "#6b7089"
paused = "#e2a478"
playing = "#b4be82"
popup_border = "#a093c7"
progress = "#89b8c2"
selection = "#6b7089"
separator = "#6b7089"
status_line = "#c6c8d1"
stopped = "#6b7089"
success = "#b4be82"
text_muted = "#6b7089"
time_text = "#c6c8d1"
warning = "#e2a478"
