[colors]
artwork_area = "#1f1f28"
background = "#1f1f28"
border = "#727169"
border_focused = "#7e9cd8"
error = "#c34043"
foreground = "#dcd7ba"
highlight = "#c0a36e"
lyrics_background = "#1f1f28"
lyrics_border = "#727169"
lyrics_border_focused = "#7e9cd8"
lyrics_highlight = "#6a9589"
lyrics_text = "#727169"
paused = "#c0a36e"
playing = "#76946a"
popup_border = "#957fb8"
progress = "#6a9589"
selection = "#2d4f67"
separator = "#727169"
status_line = "#dcd7ba"
stopped = "#727169"
success = "#76946a"
text_muted = "#727169"
time_text = "#dcd7ba"
warning = "#c0a36e"
