[colors]
artwork_area = "#0f191c"
background = "#0f191c"
border = "#688060"
border_focused = "#50b45a"
error = "#23755a"
foreground = "#426644"
highlight = "#ffd700"
lyrics_background = "#0f191c"
lyrics_border = "#688060"
lyrics_border_focused = "#50b45a"
lyrics_highlight = "#50b45a"
lyrics_text = "#688060"
paused = "#ffd700"
playing = "#82d967"
popup_border = "#409931"
progress = "#50b45a"
selection = "#18282e"
separator = "#688060"
status_line = "#426644"
stopped = "#688060"
success = "#82d967"
text_muted = "#688060"
time_text = "#426644"
warning = "#ffd700"
