[colors]
artwork_area = "#272822"
background = "#272822"
border = "#75715e"
border_focused = "#66d9ef"
error = "#f92672"
foreground = "#f8f8f2"
highlight = "#e6db74"
lyrics_background = "#272822"
lyrics_border = "#75715e"
lyrics_border_focused = "#66d9ef"
lyrics_highlight = "#a1efe4"
lyrics_text = "#75715e"
paused = "#e6db74"
playing = "#a6e22e"
popup_border = "#ae81ff"
progress = "#a1efe4"
selection = "#49483e"
separator = "#75715e"
status_line = "#f8f8f2"
stopped = "#75715e"
success = "#a6e22e"
text_muted = "#75715e"
time_text = "#f8f8f2"
warning = "#e6db74"
