[colors]
artwork_area = "#080808"
background = "#080808"
border = "#949494"
border_focused = "#80a0ff"
error = "#ff5d5d"
foreground = "#bdbdbd"
highlight = "#e3c78a"
lyrics_background = "#080808"
lyrics_border = "#949494"
lyrics_border_focused = "#80a0ff"
lyrics_highlight = "#79dac8"
lyrics_text = "#949494"
paused = "#e3c78a"
playing = "#8cc85f"
popup_border = "#cf87e8"
progress = "#79dac8"
selection = "#949494"
separator = "#949494"
status_line = "#bdbdbd"
stopped = "#949494"
success = "#8cc85f"
text_muted = "#949494"
time_text = "#bdbdbd"
warning = "#e3c78a"
