[colors]
artwork_area = "#2e3440"
background = "#2e3440"
border = "#3b4252"
border_focused = "#88c0d0"
error = "#bf616a"
foreground = "#d8dee9"
highlight = "#ebcb8b"
lyrics_background = "#2e3440"
lyrics_border = "#3b4252"
lyrics_border_focused = "#88c0d0"
lyrics_highlight = "#88c0d0"
lyrics_text = "#4c566a"
paused = "#ebcb8b"
playing = "#a3be8c"
popup_border = "#b48ead"
progress = "#88c0d0"
selection = "#4c566a"
separator = "#3b4252"
status_line = "#d8dee9"
stopped = "#4c566a"
success = "#a3be8c"
text_muted = "#4c566a"
time_text = "#d8dee9"
warning = "#ebcb8b"
