[colors]
artwork_area = "#282c34"
background = "#282c34"
border = "#3e4452"
border_focused = "#61afef"
error = "#e06c75"
foreground = "#abb2bf"
highlight = "#e5c07b"
lyrics_background = "#282c34"
lyrics_border = "#3e4452"
lyrics_border_focused = "#61afef"
lyrics_highlight = "#56b6c2"
lyrics_text = "#3e4452"
paused = "#e5c07b"
playing = "#98c379"
popup_border = "#c678dd"
progress = "#56b6c2"
selection = "#5c6370"
separator = "#3e4452"
status_line = "#abb2bf"
stopped = "#3e4452"
success = "#98c379"
text_muted = "#3e4452"
time_text = "#abb2bf"
warning = "#e5c07b"
