[colors]
artwork_area = "#292d3e"
background = "#292d3e"
border = "#676e95"
border_focused = "#82aaff"
error = "#ff5572"
foreground = "#bfc7d5"
highlight = "#ffcb6b"
lyrics_background = "#292d3e"
lyrics_border = "#676e95"
lyrics_border_focused = "#82aaff"
lyrics_highlight = "#89ddff"
lyrics_text = "#676e95"
paused = "#ffcb6b"
playing = "#a9c77d"
popup_border = "#c792ea"
progress = "#89ddff"
selection = "#7580b8"
separator = "#676e95"
status_line = "#bfc7d5"
stopped = "#676e95"
success = "#a9c77d"
text_muted = "#676e95"
time_text = "#bfc7d5"
warning = "#ffcb6b"
