[colors]
artwork_area = "#faf4ed"
background = "#faf4ed"
border = "#f2e9e1"
border_focused = "#56949f"
error = "#b4637a"
foreground = "#575279"
highlight = "#ea9d34"
lyrics_background = "#faf4ed"
lyrics_border = "#f2e9e1"
lyrics_border_focused = "#56949f"
lyrics_highlight = "#56949f"
lyrics_text = "#9893a5"
paused = "#ea9d34"
playing = "#286983"
popup_border = "#907aa9"
progress = "#56949f"
selection = "#dfdad9"
separator = "#f2e9e1"
status_line = "#575279"
stopped = "#9893a5"
success = "#286983"
text_muted = "#9893a5"
time_text = "#575279"
warning = "#ea9d34"
