[colors]
artwork_area = "#fdf6e3"
background = "#fdf6e3"
border = "#eee8d5"
border_focused = "#268bd2"
error = "#dc322f"
foreground = "#586e75"
highlight = "#b58900"
lyrics_background = "#fdf6e3"
lyrics_border = "#eee8d5"
lyrics_border_focused = "#268bd2"
lyrics_highlight = "#2aa198"
lyrics_text = "#657b83"
paused = "#b58900"
playing = "#859900"
popup_border = "#d33682"
progress = "#2aa198"
selection = "#eee8d5"
separator = "#eee8d5"
status_line = "#586e75"
stopped = "#657b83"
success = "#859900"
text_muted = "#657b83"
time_text = "#586e75"
warning = "#b58900"
