[colors]
artwork_area = "#002b36"
background = "#002b36"
border = "#073642"
border_focused = "#268bd2"
error = "#dc322f"
foreground = "#839496"
highlight = "#b58900"
lyrics_background = "#002b36"
lyrics_border = "#073642"
lyrics_border_focused = "#268bd2"
lyrics_highlight = "#2aa198"
lyrics_text = "#586e75"
paused = "#b58900"
playing = "#859900"
popup_border = "#d33682"
progress = "#2aa198"
selection = "#073642"
separator = "#073642"
status_line = "#839496"
stopped = "#586e75"
success = "#859900"
text_muted = "#586e75"
time_text = "#839496"
warning = "#b58900"
