[colors]
artwork_area = "#262335"
background = "#262335"
border = "#595959"
border_focused = "#03edf9"
error = "#fe4450"
foreground = "#ffffff"
highlight = "#fede5d"
lyrics_background = "#262335"
lyrics_border = "#595959"
lyrics_border_focused = "#03edf9"
lyrics_highlight = "#03edf9"
lyrics_text = "#595959"
paused = "#fede5d"
playing = "#72f1b8"
popup_border = "#ff7edb"
progress = "#03edf9"
selection = "#1a1825"
separator = "#595959"
status_line = "#ffffff"
stopped = "#595959"
success = "#72f1b8"
text_muted = "#595959"
time_text = "#ffffff"
warning = "#f3e70f"
