[colors]
artwork_area = "#1a1b26"
background = "#1a1b26"
border = "#15161e"
border_focused = "#7aa2f7"
error = "#f7768e"
foreground = "#c0caf5"
highlight = "#e0af68"
lyrics_background = "#1a1b26"
lyrics_border = "#15161e"
lyrics_border_focused = "#7aa2f7"
lyrics_highlight = "#7dcfff"
lyrics_text = "#414868"
paused = "#e0af68"
playing = "#9ece6a"
popup_border = "#bb9af7"
progress = "#7dcfff"
selection = "#283457"
separator = "#15161e"
status_line = "#c0caf5"
stopped = "#414868"
success = "#9ece6a"
text_muted = "#414868"
time_text = "#c0caf5"
warning = "#e0af68"
